version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.13
    container_name: elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./data/es6:/usr/share/elasticsearch/data
    restart: unless-stopped

  database:
    image: mariadb:10.6
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/initdb:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - activecollab
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8070:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=${MYSQL_USER:-app}
      - PMA_PASSWORD=${MYSQL_PASSWORD:-app_password}
      - UPLOAD_LIMIT: 300M
    depends_on:
      - database
    restart: unless-stopped

  activecollab:
    build: .
    container_name: activecollab
    ports:
      - 8888:80
    volumes:
      - ./data/app:/var/www/html
    depends_on:
      - database
      - elasticsearch
    restart: unless-stopped
